# Generated by Django 5.2.7 on 2025-11-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='bicicletas/'),
        ),
    ]
