# Generated by Django 5.2.7 on 2025-11-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0002_bicicleta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
