# Generated by Django 5.2.7 on 2025-10-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ingredientes', models.TextField()),
                ('instrucciones', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recetas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
