# Generated by Django 5.2.7 on 2025-10-31 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automovil',
            old_name='anio',
            new_name='año',
        ),
    ]
