# Generated by Django 5.2.7 on 2025-11-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('anio', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bicicletas/')),
            ],
        ),
    ]
