# Generated by Django 5.2.7 on 2025-10-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ingredientes', models.TextField()),
                ('instrucciones', models.TextField()),
                ('tiempo_preparacion', models.IntegerField(help_text='Tiempo en minutos')),
                ('porciones', models.IntegerField()),
            ],
        ),
    ]
