# Generated by Django 5.2.7 on 2025-10-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_by',
            new_name='creator',
        ),
    ]
