# Generated by Django 5.2.6 on 2025-10-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='actualizada_en',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='prioridad',
        ),
    ]
