# Generated by Django 5.2.7 on 2025-11-09 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0003_alter_bicicleta_precio'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.bicicleta')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='bicicletas',
            field=models.ManyToManyField(related_name='ordenes', through='ordenes.DetalleOrden', to='bicicletas.bicicleta'),
        ),
    ]
