# Generated by Django 5.2.7 on 2025-11-13 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_detalleorden_orden_bicicletas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleorden',
            options={'verbose_name': 'Detalle de Orden', 'verbose_name_plural': 'Detalles de Órdenes'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ['-fecha'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Órdenes'},
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ordenes.orden'),
        ),
    ]
