# Generated by Django 5.2.7 on 2025-11-19 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_evento', models.CharField(choices=[('parque', 'Salida a Parque'), ('volcan', 'Salida a Volcán'), ('ruta_costera', 'Ruta Costera'), ('montana', 'Mountain Bike'), ('urbano', 'Tour Urbano')], max_length=20)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('intermedio', 'Intermedio'), ('dificil', 'Difícil'), ('experto', 'Experto')], max_length=15)),
                ('destino', models.CharField(help_text='Lugar de destino', max_length=200)),
                ('punto_encuentro', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField()),
                ('duracion_horas', models.DecimalField(decimal_places=1, help_text='Duración en horas', max_digits=4)),
                ('distancia_km', models.DecimalField(decimal_places=1, help_text='Distancia en kilómetros', max_digits=5)),
                ('cupo_maximo', models.PositiveIntegerField(default=20)),
                ('cupo_disponible', models.PositiveIntegerField(default=20)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio por persona', max_digits=10)),
                ('incluye_guia', models.BooleanField(default=True)),
                ('incluye_seguro', models.BooleanField(default=True)),
                ('incluye_hidratacion', models.BooleanField(default=True)),
                ('incluye_snacks', models.BooleanField(default=False)),
                ('nivel_minimo', models.CharField(blank=True, help_text='Requisitos mínimos para participar', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('num_personas', models.PositiveIntegerField(default=1, help_text='Número de personas')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Alergias, condiciones médicas, etc.')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('pagado', models.BooleanField(default=False)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_eventos', to='app_clientes.cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='app_eventos.evento')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('evento', 'cliente')},
            },
        ),
    ]
